import test from 'node:test';import assert from 'node:assert/strict';import {createApp} from '../server/index.js';import {Store} from '../server/storage.js';
test('responsive assets are small, compressed, cached and revalidated',async t=>{const app=await createApp({dbFile:':memory:'});await new Promise(r=>app.server.listen(0,'127.0.0.1',r));t.after(()=>app.close());const base=`http://127.0.0.1:${app.server.address().port}`;const js=await fetch(base+'/app.js',{headers:{'Accept-Encoding':'br'}});assert.equal(js.headers.get('content-encoding'),'br');assert.ok(Number(js.headers.get('content-length'))<18000);assert.match(await js.text(),/function home/);const img=await fetch(base+'/cards/play/KS-640.webp');assert.ok(Number(img.headers.get('content-length'))<20000);const re=await fetch(base+'/cards/play/KS-640.webp',{headers:{'If-None-Match':img.headers.get('etag')}});assert.equal(re.status,304);const head=await fetch(base+'/cards/play/back-320.webp',{method:'HEAD'});assert.equal(head.status,200);assert.equal(await head.text(),'');});
test('WorkOS identity linking preserves guest stats and cannot merge by email or steal another linked seat',()=>{const store=new Store(':memory:');try{const guest=store.create('Mia');store.stats(guest.id,s=>s.hands=5);const key=store.session(guest.id);const first=store.workosPlayer({id:'user_first',email:'mia@example.com'},guest.id);assert.equal(first.id,guest.id);assert.equal(first.stats.hands,5);assert.equal(store.resolve(key),null);assert.equal(first.authProvider,'workos');const another=store.workosPlayer({id:'user_second',email:'mia@example.com'},guest.id);assert.notEqual(another.id,guest.id);assert.equal(store.workosPlayer({id:'user_first',email:'changed@example.com'}).id,guest.id);}finally{store.close();}});
test('WorkOS callback requires browser-bound state, consumes it once and preserves guest identity',async t=>{
 let exchanged=0;const client={userManagement:{getAuthorizationUrlWithPKCE:async()=>({url:'https://authkit.example/login?state=state123',state:'state123',codeVerifier:'verifier'}),authenticateWithCode:async args=>{assert.equal(args.codeVerifier,'verifier');exchanged++;return {user:{id:'user_test',firstName:'Alex'},sealedSession:'sealed'};},loadSealedSession:()=>({authenticate:async()=>({authenticated:true,user:{id:'user_test'}})})}};
 const app=await createApp({dbFile:':memory:',publicUrl:'https://partydeck.example',authOptions:{apiKey:'test',clientId:'client_test',password:'x'.repeat(32),client}});await new Promise(r=>app.server.listen(0,'127.0.0.1',r));t.after(()=>app.close());const base=`http://127.0.0.1:${app.server.address().port}`;const g=app.store.create('Alex');const session=app.store.session(g.id);
 const start=await fetch(base+'/auth/login?returnTo=https://evil.example',{headers:{cookie:'table_session='+session},redirect:'manual'});assert.equal(start.status,302);const binding=start.headers.getSetCookie().find(c=>c.startsWith('partydeck_login=')).split(';')[0];
 assert.equal((await fetch(base+'/auth/callback?state=state123&code=code',{redirect:'manual'})).status,400);assert.equal(exchanged,0);
 const complete=await fetch(base+'/auth/callback?state=state123&code=code',{headers:{cookie:binding},redirect:'manual'});assert.equal(complete.status,302);assert.equal(complete.headers.get('location'),'/');assert.equal(exchanged,1);assert.ok(complete.headers.getSetCookie().some(c=>c.startsWith('partydeck_auth=sealed;')&&c.includes('HttpOnly')&&c.includes('Secure')));assert.equal(app.store.resolve(session),null);
 assert.equal((await fetch(base+'/auth/callback?state=state123&code=code',{headers:{cookie:binding},redirect:'manual'})).status,400);assert.equal(exchanged,1);
 const me=await (await fetch(base+'/api/me',{headers:{cookie:'partydeck_auth=sealed'}})).json();assert.equal(me.profile.id,g.id);assert.equal(me.auth.workos,true);
});
